### ISSUE TITLE
Reference files mentioned in the config.yaml missing

### ISSUE THREAD

**Issue by parth2608** [raphael-group/CalicoST#1]
Hi,

Do we need to have the reference files for the following variables mentioned in the config.yaml file:
-geneticmap_file
-hgtable_file
-filtergenelist_file
-filterregion_file

I am also facing issues with the rule prepare_calicost_data "ERROR - outs directory doesn't have a filtered_feature_bc_matrix.h5 or filtered_feature_bc_matrix.h5ad file!", what should be the file structure? Where should be the "outs" folder located, same folder as the scripts or somewhere else?

It would be very helpful to have some kind of structured instructions for the file structures to successfully run the workflow.

Also, it will be helpful to get access to the google drive folder, so that I can run the example provided by you before running it on my data.

Thank you!

**Comment by lanting52119** [comment]
You can check `{calicost_dir}/logs/prepare_calicost_data.log` and `utils_IO.py`. I got the same issue with you and found that you need to link to your h5 file to your `spaceranger_dir` (specified in `config.yaml`) and your spatial coordinates csv to `spaceranger_dir/spatial/`. E.g. this is what I did:
`h5_file=filtered_feature_bc_matrix.h5`
`ln -sf -T $input_dir/s${sample_id}_${h5_file} $output_dir/${sample_id}/${h5_file}`
spatial csv is similar but under different directory.

I highly suggest the developers to add location of h5 file and spatial location csv to the config file of snakemake pipeline as the if-elif-else check in `utils_IO.py` is so strict.

**Comment by Congm12** [comment]
Thank you for the suggestion. The assumed directory structure follows the standard spaceranger output (https://www.10xgenomics.com/support/software/space-ranger/latest/analysis/outputs/output-overview) of 10x Visium data. But we'll consider that in the next version of the software.

**Comment by lanting52119** [comment]
My space-ranger output of spatial coordinates appear to be `tissue_positions.list.csv` - perhaps because of different version of spaceranger used. (What it appear in utils_IO.py are `tissue_positions_list.csv` and `tissue_positions.csv`.)
