### ISSUE TITLE
Compatibility with Visium CytAssist?

### ISSUE THREAD

**Issue by vravik** [raphael-group/CalicoST#11]
Hello Team,

I am very excited to try out this tool on our ST datasets. However most samples we have profiled recently have been using the Visium CytAssist technology, which I believe is probe based expression profiling. I was wondering if CalicoST can be used with this data? I know I couldn't use Numbat on these samples.

Thank you

**Comment by Congm12** [comment]
Hi,

CalicoST currently requires the BAF information from sequencing-based ST technologies and does not support probe-based ones. We plan to evaluate the performance of CalicoST using only the expression information and include that option in a future lease.

At the mean time, we refer you to STARCH, which infers total copy numbers and leverages the spatial information. Particularly, the develop branch has the option for using the hexagonal grid in Visium layouts by specifying `--platform Visium`
Publication: https://iopscience.iop.org/article/10.1088/1478-3975/abbe99
Github: https://github.com/raphael-group/STARCH/tree/develop

Best,
Cong
