### ISSUE TITLE
parse_final_snp error

### ISSUE THREAD

**Issue by al3xmlt030** [raphael-group/CalicoST#13]
Hello,
I am trying to rerun your analysis on one of your prostate samples patient 2

during the phasing step I stumbled in following errror

```
/dh-projects/ag-ishaque/analysis/malta/PhD/spatial/CalicoST/utils/get_snp_matrix.py:81: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_snp = pd.read_csv(cellsnp_base, comment="#", sep="\t", names=["tmpCHR", "POS", "ID", "REF", "ALT", "QUAL", "FILTER", "INFO"])
Traceback (most recent call last):
  File "/dh-projects/ag-ishaque/analysis/malta/PhD/spatial/CalicoST/utils/get_snp_matrix.py", line 183, in <module>
    cell_snp_Aallele, cell_snp_Ballele, unique_snp_ids = cell_by_gene_lefthap_counts(args.cellsnplite_result_dir, args.eagle_out_dir, barcode_list)
  File "/dh-projects/ag-ishaque/analysis/malta/PhD/spatial/CalicoST/utils/get_snp_matrix.py", line 97, in cell_by_gene_lefthap_counts
    phased_AD = np.where( (df_snp.GT.values == "0|1").reshape(-1,1), AD.A, (DP-AD).A )
AttributeError: 'csr_matrix' object has no attribute 'A'

```
my phasing folder looks like this:
![grafik](https://github.com/user-attachments/assets/96960f59-7820-44be-a39f-ea5355ee85da)

where head of one phased example file looks like this:
![grafik](https://github.com/user-attachments/assets/a10994fc-b307-4f63-9779-18b869c019a1)

here a overview of my config file

```
# path to executables or their parent directories
calicost_dir: /dh-projects/ag-ishaque/analysis/malta/PhD/spatial/CalicoST 
eagledir: /dh-projects/ag-ishaque/analysis/malta/PhD/spatial/CalicoST/external/Eagle_v2.4.1

# running parameters
# samtools sort (only used when joingly calling from multiple slices)
samtools_sorting_mem: "4G"
# cellsnp-lite
UMItag: "Auto"
cellTAG: "CB"
nthreads_cellsnplite: 20
region_vcf: /dh-projects/ag-ishaque/analysis/malta/PhD/spatial/CalicoST/SNPPanel/genome1K.phase3.SNP_AF5e4.chr1toX.hg38.vcf.gz
# Eagle phasing
phasing_panel: /dh-projects/ag-ishaque/analysis/malta/PhD/spatial/HTAN_prostate_CalicoST/1000G_hg38
chromosomes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

# input
spaceranger_dir: /dh-projects/ag-ishaque/analysis/malta/PhD/spatial/HTAN_prostate_CalicoST/sampleV2_5/outs/
# output
output_snpinfo: /dh-projects/ag-ishaque/analysis/malta/PhD/spatial/HTAN_prostate_CalicoST

```
allignment was done by **spaceranger-3.1.1** 

thank you in advance!

**Comment by al3xmlt030** [comment]
changed script:  `phased_AD = np.where( (df_snp.GT.values == "0|1").reshape(-1,1), AD.toarray(), (DP-AD).toarray())`

now it is working...

or just downgrade scipy to 1.13.1

**Comment by Congm12** [comment]
Thank you for checking! Yes, this is due to the version incompatibility with scipy, we are working on an updated version of the code and will fix the scipy compatibility in the new version as well.

**Comment by wangmengbo** [comment]
maybe just include scipy version in the dependency...

**Comment by al3xmlt030** [comment]
related error occurred for numpy.
np.NAN and np.nan is used interchangeable. Within the numpy version included only np.nan is defined

**Comment by Congm12** [comment]
Thank you for the suggestion! We updated the `environment.yml` and `setup.py` files to specify the version of numpy and scipy.
