### ISSUE TITLE
whether this tool could be applied on the dataset that missing the bam file

### ISSUE THREAD

**Issue by Danne1210** [raphael-group/CalicoST#19]
Hi,
thanks for your wonderful. I have some spatial transcriptomics dataset (3'-sequencing based), while the bam file is missing. I wonder whether the tool CalicoST could be applied to the spatial dataset, to infer the cnv and other results, such as the tumour microregion?

**Comment by Congm12** [comment]
Hi,

CalicoST currently requires the BAM file to compute the BAF information. We refer you to STARCH, which infers total copy numbers from gene expression information and doesn't require a BAM file. The develop branch has the option for using the hexagonal grid in Visium layouts by specifying --platform Visium
Publication: https://iopscience.iop.org/article/10.1088/1478-3975/abbe99
Github: https://github.com/raphael-group/STARCH/tree/develop

Best,
Cong

**Comment by Danne1210** [comment]
> Hi,
> 
> CalicoST currently requires the BAM file to compute the BAF information. We refer you to STARCH, which infers total copy numbers from gene expression information and doesn't require a BAM file. The develop branch has the option for using the hexagonal grid in Visium layouts by specifying --platform Visium Publication: https://iopscience.iop.org/article/10.1088/1478-3975/abbe99 Github: https://github.com/raphael-group/STARCH/tree/develop
> 
> Best, Cong

Hi, thanks for your prompt reply. The dataset is from stereo-seq and has been cell segmented. Then, I wonder: 1. If I have the bam file in future, whether could I use CalicoST on stereo-seq data? Since CalicoST have the wonderful function to infer the tumor multiregions and CNV clones. 2. Does STARCH could be applied to the cell-segmented Stereo-seq data?
